[[OpenJpeg]]
arch = "aarch64"
git-tree-sha1 = "25363792d62770562e616c24498e9cdece9e772e"
os = "macos"

    [[OpenJpeg.download]]
    sha256 = "e81ee1248f2af5d77d3ee9d5cfc6091eb07ce4caa9a62fa55b5e1de65226aff0"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.aarch64-apple-darwin.tar.gz"
[[OpenJpeg]]
arch = "aarch64"
git-tree-sha1 = "0af8837b5b2630b96ddb24ba93241e60ebb09cc9"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "17d0cdc2db06cb2edc80f303be4a4eee5489ce60f67a211739a9b84ae5b2adae"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.aarch64-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "aarch64"
git-tree-sha1 = "5b9f33b44d26fbc1c5754f7ee6d5f142dbc0e9ee"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "d4b74eef5a2d64a4cfcedb328031ecb948f037178bee8820fabd56d27dd1735a"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.aarch64-linux-musl.tar.gz"
[[OpenJpeg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "867d418212bde51853c8a4ede6ad358b76e7aa1b"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "bd7c2e02473bd147efeade9523dc79104cb27c6b1f63589ff1969391a3454161"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[OpenJpeg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f1bfd4ee29894c2cdfd0abb3c8fcc1f990bbeef"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "2bdac9d83e61c1dc4c57341cd3c7502ccabdfaecb4a4fef350706b2639675ec0"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[OpenJpeg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af2665f5a169a7d9d1b62e18f9e3bee797a46ae7"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "38cae5409ee09982e00ca58afcc738e861b1915b296070d84be0baee4cfcdf45"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[OpenJpeg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec0af43c348283d55e98b812d69fbb7851d6e772"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "0373dcdf2f0a9220a4a8a6c96644830493da726763a872c7c72855e99252f53b"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[OpenJpeg]]
arch = "i686"
git-tree-sha1 = "a972e3cc90a2a298fb6569b705b91b25237e1bd9"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "31b818cfefae62100b6d58df07e8b0ae0012d1977dff3c72e91c05dd2afa0ceb"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.i686-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "i686"
git-tree-sha1 = "fe33350386c54c515cce2749b261ca69b5d571d5"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "8dd1dbb9507c0d370f966265268ef25921e8f2e4da12b357aba02b85558e5c6e"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.i686-linux-musl.tar.gz"
[[OpenJpeg]]
arch = "i686"
git-tree-sha1 = "d85638cf5ba0ab408a0597a87faed985cf5fe44f"
os = "windows"

    [[OpenJpeg.download]]
    sha256 = "5b53ec06bb84e9dad8653e4b39809cbb60d7f29d29a073ee90660f33d219b0f6"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.i686-w64-mingw32.tar.gz"
[[OpenJpeg]]
arch = "powerpc64le"
git-tree-sha1 = "c3ce7a348b66c6304745018837e4ee03e190b86c"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "c0988eca3111ad7a66a2749fa9cb1e019f50512b66c466a929fbadbe119e25a9"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "923975814f315299b99546f602d81fe55674503c"
os = "macos"

    [[OpenJpeg.download]]
    sha256 = "41c63d9982844bce5e9749839414c405d2ef4e46922effd44250208576863356"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.x86_64-apple-darwin.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "75ff570708c711448e25a30cd718c85749070d12"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "24c8adb938d5d086e42f1fe89bdf77217aecf9b7636061fe2d038f4919f2b65c"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.x86_64-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "83b1d25325e706e60c0a229c0ca6ffed651ca2a6"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "cfaf9c7da63df6e95e3f343c4ee169b8fb995d9547e48e889ac68ae03c54c624"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.x86_64-linux-musl.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "ea5b2cdaf1a97389b5a08beae2f0a4e9979e5e06"
os = "freebsd"

    [[OpenJpeg.download]]
    sha256 = "99ad28ff72af7e44805ebe3a3b1386863d4a6364e0af2ed8cb076f0bb31e9d1c"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.x86_64-unknown-freebsd.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "bf2a61cb6c6f2713658fa765a2e095e2be625117"
os = "windows"

    [[OpenJpeg.download]]
    sha256 = "bdc6d4f427fcb1514f1930a25de909d768bfbfdedfb8724a3f2211f075e22e78"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.0+0/OpenJpeg.v2.5.0.x86_64-w64-mingw32.tar.gz"
