[[OpenJpeg]]
arch = "aarch64"
git-tree-sha1 = "cba42c2e72b214c5a4beab5c23d1d0b85178bc85"
os = "macos"

    [[OpenJpeg.download]]
    sha256 = "af6884729c163e75ab6d2e34c7daeaec72ad8fbe52c13bacbd80ad8c2052479f"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.aarch64-apple-darwin.tar.gz"
[[OpenJpeg]]
arch = "aarch64"
git-tree-sha1 = "2e6a31e4458a13ef2522dc2ab0224633c3e28140"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "66a87ea817edb2154d8f1be28dc20e01a8ae70aadba11ab2db667a70b6478601"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.aarch64-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "aarch64"
git-tree-sha1 = "1582b125b8774239262061a2b845ccad964b822b"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "7515bd204d701381d1c5ecec9ec38ffac47d8e5ec5fd96c373ce5a675d15d00c"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.aarch64-linux-musl.tar.gz"
[[OpenJpeg]]
arch = "aarch64"
git-tree-sha1 = "b05d5b6188cb1affb83421475be06582265a151f"
os = "freebsd"

    [[OpenJpeg.download]]
    sha256 = "0abc409b3b935229a691b0ac131ed04cc19cee4aa4fb6d1fc5ca58bf1aa061af"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.aarch64-unknown-freebsd.tar.gz"
[[OpenJpeg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "455ed90eb9b693cabfc8df128e6bac86d66f4a67"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "b1a06be802330a1e5d62d22c36439f2a42052d7c0eea4e972539784bd5e0db70"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.armv6l-linux-gnueabihf.tar.gz"
[[OpenJpeg]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e77f6f44e6ef103d1537d2ef8a86fe9596394b79"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "d5b36962b0eedc868a0358e02acdcf8f106a7d04357b2c6cac7b6c03aa144954"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.armv6l-linux-musleabihf.tar.gz"
[[OpenJpeg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "deabba0eb63b2414446ff9082191931d17b68c97"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "529ba41edc4af397718972793a2575d02b39c0583a756091d015dc1839effead"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.armv7l-linux-gnueabihf.tar.gz"
[[OpenJpeg]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a33fd11975e67995d5565640d16febdcd7866dbe"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "470440be95e4861d702bd91277edb389ba47adfb965516226adfe5b387a14081"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.armv7l-linux-musleabihf.tar.gz"
[[OpenJpeg]]
arch = "i686"
git-tree-sha1 = "f38dc803c6d2e333ecaf27dd94202a598f0de529"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "89fb3beea742788568d24e372ed3c167e248b6c65dd7e2262c58d9cc3cd111d7"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.i686-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "i686"
git-tree-sha1 = "d253e2f7042c38078325bdd471da6e9e5f892484"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "4205a6755cea94eaafa596da9f1becfee0ea51e91d56b099101a41c8ff061b0e"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.i686-linux-musl.tar.gz"
[[OpenJpeg]]
arch = "i686"
git-tree-sha1 = "f91fdb2c08b79690cfb5cf4ac9de74d29f5b7a56"
os = "windows"

    [[OpenJpeg.download]]
    sha256 = "7399a2de0ddc88f79a0b3b4c5531f48d4a5b828a4e8497d9d647d0c14eb9c78b"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.i686-w64-mingw32.tar.gz"
[[OpenJpeg]]
arch = "powerpc64le"
git-tree-sha1 = "0cf6c8f550f59e06d2cd26135321b2c7b4dfc542"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "fd15f74b65ffdc490e9642358875a43aec10c9b9cf84f82e78cdc0f1d44a5f2f"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.powerpc64le-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "riscv64"
git-tree-sha1 = "18cec9020720b1cd0acfe475e7b24fa20f186814"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "6e206578906592b34ccc22897bb01d30dc498d3af686aaecfabea75d5a1b4b10"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.riscv64-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "0a1763a146663dcbf05881a2f856f7080a30d5b9"
os = "macos"

    [[OpenJpeg.download]]
    sha256 = "2d79f872261c0e7a2310e8cea2cedf1a99f03aa37dba595fd90df847ac6bee18"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.x86_64-apple-darwin.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "c1acc8b437fe59987120328e79d52b7a99186567"
libc = "glibc"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "1bf058be6174da171f22aa29f74ba0d823c68dfce340b41ef09638af1a83cfab"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.x86_64-linux-gnu.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "77b65a0dc933f19f2f7de0d59fb108d5912186e8"
libc = "musl"
os = "linux"

    [[OpenJpeg.download]]
    sha256 = "b0a7ea5bc04cad6281cf8c94e0c2f917030549606d19c074ddf7987b70f681b9"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.x86_64-linux-musl.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "20e0815ead909ee0138baf1ecd1d176cda408270"
os = "freebsd"

    [[OpenJpeg.download]]
    sha256 = "a894b27ee454b578aaee08c4e27c161e793c7a02a4d725981b662c8ef15a8ae2"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.x86_64-unknown-freebsd.tar.gz"
[[OpenJpeg]]
arch = "x86_64"
git-tree-sha1 = "809dd3926ad2ff487f8603d325adf4592259bf63"
os = "windows"

    [[OpenJpeg.download]]
    sha256 = "4329139737cd36a6226333e7d5b6cad12dc2e378400666a775a8446a1aaecc76"
    url = "https://github.com/JuliaBinaryWrappers/OpenJpeg_jll.jl/releases/download/OpenJpeg-v2.5.5+0/OpenJpeg.v2.5.5.x86_64-w64-mingw32.tar.gz"
