# Autogenerated wrapper script for OpenJpeg_jll for x86_64-w64-mingw32
export libopenjp2, opj_compress, opj_decompress, opj_dump

using LittleCMS_jll
using libpng_jll
using Libtiff_jll
JLLWrappers.@generate_wrapper_header("OpenJpeg")
JLLWrappers.@declare_library_product(libopenjp2, "libopenjp2.dll")
JLLWrappers.@declare_executable_product(opj_compress)
JLLWrappers.@declare_executable_product(opj_decompress)
JLLWrappers.@declare_executable_product(opj_dump)
function __init__()
    JLLWrappers.@generate_init_header(LittleCMS_jll, libpng_jll, Libtiff_jll)
    JLLWrappers.@init_library_product(
        libopenjp2,
        "bin\\libopenjp2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        opj_compress,
        "bin\\opj_compress.exe",
    )

    JLLWrappers.@init_executable_product(
        opj_decompress,
        "bin\\opj_decompress.exe",
    )

    JLLWrappers.@init_executable_product(
        opj_dump,
        "bin\\opj_dump.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
